name = "xuanju-company-homepage"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./"

[build]
command = ""
upload.format = "service-worker"
main = "index.html"

# 静态站点部署配置
# Cloudflare Pages 会自动识别并部署
